### ISSUE TITLE
Randomized event times

### ISSUE THREAD

**Issue by rlwellman** [arthurdent75/SimpleScheduler#186]
Would it be possible to randomize an event time (say plus or minus some number of minutes) to give a lived-in look to lights etc coming on and off?  I have looked around HA and as late as December 2024 folks are wishing there was a simple way to do that and there apparently isn't.

**Comment by arthurdent75** [comment]
In the scheduler, instead of turning on the light, call a script that turns on the light with a random delay.
Something like this:

```
alias: "Random Delayed Light On"
sequence:
  - variables:
      max_delay: 10  # Set the maximum delay in minutes
  - delay:
      minutes: "{{ range(0, max_delay + 1) | random }}"  # Generate a random delay between 0 and max_delay
  - service: light.turn_on
    target:
      entity_id:
        - light.living_room  # Replace with your light entity or add more
        - light.kitchen  # Example of multiple lights
mode: single  # Prevents multiple executions at the same time
```

In the actual beta release (2.9.4), parameters can also be passed to the script.
You could for example pass the max_delay and/or the lighs from the scheduler as a parameter.

**Example scenario with parametric script**

1. Setup a group of lights e.g.: *light.my_decoy_lights*

2. Create this script:

```
alias: "Random Delayed Light On (With Parameters)"
sequence:
  - variables:
      max_delay: "{{ max_delay | default(10) | int }}"  # Default max delay is 10 minutes if not provided
      light_group: "{{ light_group | default('light.living_room') }}"  # Default light group if not provided

  - delay:
      minutes: "{{ range(0, max_delay + 1) | random }}"  # Random delay between 0 and max_delay

  - service: light.turn_on
    target:
      entity_id: "{{ light_group }}"  # Turns on the provided group of lights

mode: single  # Prevents multiple simultaneous executions
```

3. Create a scheduler to call the previous script and set the ON time like this:

`20:30>J{"max_delay":"60","light_group":"light.my_decoy_lights"}`

With a little fantasy (and/or a little help from chatGPT & friends), you could also add the random OFF 😉
